# Generated by Django 5.0.2 on 2024-02-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0004_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="about",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
